### ISSUE TITLE
One to one mapping not working properly

### ISSUE THREAD

**Issue by Abhi6921** [Abhi6921/Java_student_api#1]
Hello Wim,

I am trying to create a @onetoone mapping for my student api for the time being, but it doesn't seem to work properly. I dont seem to understand what the issue could you please look at my code, and tell me what could I be doing wrong?

Regards,
Abhishek Narvekar

**Comment by wimmelstein** [comment]
Hi Abishek,
If you submit an issue you should be more precise. Something went wrong doesn't tell me anything. Does your application start up? If not, are there error messages? What would you expect to see? How does the actual result differ?

You cannot expect me to look at your code, and magically know what's wrong.
